test: &default

  # Credentials for REST APIs
  client_id: Acql9rBVHp8c7rUkIATe_qQ_hGun83B6YVp6Tpy7tio-ewGXOp9sjSkW0hahjkEczMT3T9LeiyI0RmNV
  client_secret: EFHXbeLaWpFFM9HjB1Yjpi-f0PjfadGPxfEGhjgEyOW0V9PVjGgxUQrnXDkBBfsdeWED3zgKX3WYoZca

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
#  app_id: APP-80W284485P519543T
#  username: jb-us-seller_api1.paypal.com
#  password: WX4WTU3S8MY44S7F
#  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
#  sandbox_email_address: 'sofka.fake.dev@gmail.com'

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
#  mode: live
